---
sidebar: sidebar 
permalink: index.html 
keywords: interoperability matrix tool, imt, ONTAP SAN Host Simplified 
summary: 'NetApp互操作性表工具(IMT)是一款基于Web的应用程序。使用IMT、您可以搜索符合NetApp指定的标准和要求的NetApp产品和组件的配置。' 
---
= 互操作性表工具概述
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp互操作性表工具(IMT)是一款基于Web的应用程序。使用IMT、您可以搜索符合NetApp指定的标准和要求的NetApp产品和组件的配置。IMT维护着一个配置存储库、并提供了一个用户友好的界面、便于您轻松访问受支持的配置信息。

您可以使用以下标准浏览器之一从NetApp支持站点访问IMT：

* 对于 Windows ：
+
** Chrome N和N-1
** Mozilla Firefox N和N-1
+

NOTE: n表示最新版本。

** Internet Explorer 11和Edge


* 对于Mac：
+
** Chrome N和N-1
** Mozilla Firefox N和N-1
** Safari 8及更高版本


+

NOTE: 互操作性表工具可接受URL链接以及标准、以简化某些使用情形。单击其他工具中的链接以打开IMT时、您可能会进入实践页面、而不是主页、其中预先选择了解决方案和某些组件。





== 开始使用互操作性表工具

互操作性表工具(IMT)是一款基于Web的应用程序、可用于搜索使用不同解决方案、配置、组件和类别的产品的兼容性。

为便于导航和清晰起见，此工具分为三页：*输入条件*、*细化搜索条件*和*结果*。您必须在第一页上输入搜索条件。根据您的搜索条件，您可以在*Refine Search Criteries*页面中查看您的产品的兼容性。本主题将简要介绍如何使用IMT。

您可以在*results*页面中查看结果。使用此工具、您可以搜索组件、进行选择、构建标准以及查看您的产品的可支持性。

您可以完成以下任务：

[cols="25,65"]
|===
| 正在使用此页面... | 您可以执行以下任务 ... 


| 输入条件 | 输入搜索条件并搜索解决方案、组件、配置和类别。如果您知道解决方案名称，可以使用*简化的ONTAP SAN主机*或*解决方案搜索*功能搜索解决方案。如果您知道组件名称，可以使用*列表和查找*或*高级搜索*功能搜索组件。 


| 细化搜索条件 | 查找有关您的商品的兼容解决方案、组件、配置和类别的更明确的"是"或"否"答案。您可以选择使用*更改准则*或*尝试其他方法*更改在第一页输入的初始准则。在每个类别的组件上应用筛选器、以查找最适合您的产品的配置。使用*Clear All*或*undo*图标删除应用的过滤器。 


| 结果 | 单击*继续*、*>*图标或第二页上的拆分器后，查看*results*页。您可以查看配置的组件、注释和历史记录详细信息、对搜索结果进行排序、查看选定的搜索条件、修改搜索条件、筛选搜索结果以及将搜索结果导出到Microsoft Excel工作表。 
|===


== 使用互操作性表工具主页

通过互操作性表工具(IMT)主页，您可以使用*简化的ONTAP主机*、*解决方案搜索、列表和查找*以及*高级搜索*。

您可以使用*set as default*星号将其中任何选项设置为默认搜索。单击任一选项后、相关页面将打开、以浏览兼容配置。


NOTE: 要查找以前保存的搜索，可以使用*保存的搜索*菜单。如果找不到所需的配置，请单击“*找不到配置?*”菜单并报告问题。
