---
sidebar: sidebar 
permalink: working-with-solution-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: '您可以搜索不同的存储解决方案、并在搜索条件中添加或删除解决方案。您可以使用"解决方案搜索"页面中的搜索文本框搜索特定解决方案。"解决方案搜索"字段将显示经常访问的解决方案。' 
---
= 使用解决方案搜索
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以搜索不同的存储解决方案、并在搜索条件中添加或删除解决方案。您可以使用*解决方案搜索*页面中的搜索文本框来搜索特定的解决方案。经常访问的解决方案显示在*解决方案搜索*字段中。



== 关于此任务

“*解决方案搜索*”页包括一个*解决方案目录*选项卡和一个*映射助手*选项卡。在*Mapping Assistant"(*映射助手*)选项卡中，您可以通过选择*Map by Category (按类别映射)*或*Map by Solution (按解决方案映射)*来查看选定解决方案的类别。



=== 解决方案目录

在*解决方案目录*选项卡上，可以使用过滤器条*过滤解决方案*。

如果要包括此类配置，还可以选择*包括PVR必需配置、EOS配置和已废弃配置*。



=== 映射助理

以下是两种类型的工作区模式：

* *按类别映射*：您可以从列出的类别中选择一个类别，并启用包含选定类别的所有解决方案，有效的解决方案位于列表顶部。您可以选择添加一个或多个支持的解决方案。您可以使用*搜索类别*文本框搜索特定类别。
* *按解决方案映射*：您可以从列出的解决方案中选择一个解决方案，并启用包含选定解决方案的所有解决方案，有效解决方案位于列表顶部。您可以选择添加一个或多个支持的解决方案。您可以使用*搜索解决方案*文本框搜索特定类别。


如果要包括此类配置，还可以选择*包括PVR必需配置、EOS配置和已废弃配置*。

完成后，您可以在*选定存储解决方案*下看到您选择的项目。*单击查看细化搜索条件*或*跳至结果*。



=== 引导式搜索

选择解决方案时，将启用*引导式搜索*。*引导式搜索*提供了一个引导式工作流，用于进一步细化标准。



== 步骤

. 单击主页中的*解决方案搜索*。
. 选择要使用的视图：
+
.. 单击*Expert View*可查看高级标准选项。
.. 单击*引导式视图*可查看简化的标准选项和引导式标准选项。


. 在*新用户视图*中，选择显示的搜索准则选项：
+
.. 单击*Skip*移动到下一个组件而不进行选择。您可以根据需要单击*Unski*返回组件。
.. 在前五个选择后，单击*显示更多*以继续细化搜索条件。您可以通过单击*显示更少*返回上一视图。
.. 完成后，单击*查看结果*以查看搜索条件支持的配置。


. 在*Expert View*中，选择要用于各种组件的搜索条件。我们建议您从左向右移动、因为每个选择都会细化其余条件。您不必为每个组件进行选择。
+
.. 完成后，单击*查看结果*以查看搜索条件支持的配置。


. 您也可以在*解决方案搜索*中执行以下操作：
+
.. 单击书籍图标可查看适用于您选择的策略和准则。
.. 单击链图标可为您的选择生成一个可共享的URL、您可以与其他人共享此URL。
.. 选择撤消图标以清除所有选择并重新开始。


. 在结果屏幕中、您可以执行以下操作：
+
.. 查看有关您的配置的详细信息、警报和信息通知。
.. 单击星号图标将此搜索设为收藏项。命名并描述配置。这将成为保存的搜索、可从"保存的搜索"菜单中查看。您也可以在此处订阅配置、更改后会通知您。如果您订阅，您还会在*subscribes*菜单下看到此列表。
.. 将鼠标悬停在*使用*构建端到端视图上可查找其他受支持的解决方案。
.. 单击*What if*以更改组件并浏览其他兼容性选项。



