---
sidebar: sidebar 
permalink: working-with-ontap-san-host-solutions-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: 检查ONTAP版本与闪存或光纤存储版本组合的兼容性。您可以进一步细化每个相关组件的兼容性搜索 
---
= 使用ONTAP SAN主机简化搜索
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
检查ONTAP版本与闪存或光纤存储版本组合的兼容性。您可以进一步细化每个相关组件的兼容性搜索。



== 关于此任务

您可以检查SAN上的闪存或光纤存储设备与要使用的ONTAP版本以及其他相关组件之间的兼容性。您可以在*Expert View*或*ANCHODORE*视图之间进行选择。


NOTE: 单击*设为默认值*选项可在您打开IMT时自动打开*简化的ONTAP SAN主机*搜索。



== 步骤

. 在主页中单击“*简化的ONTAP SAN主机*”。
. 选择要使用的视图：
+
.. 单击*Expert View*可查看高级标准选项。
.. 单击*引导式视图*可查看简化和引导式标准选项。


. 在*新用户视图*中，选择显示的搜索准则选项。
+
.. 单击*Skip*移动到下一个组件而不进行选择。您可以根据需要单击*Unski*返回组件。
.. 完成后，单击*查看结果*以查看搜索条件支持的配置。


. 在*Expert View*中，选择要用于各种组件的搜索条件。我们建议您从左向右移动、因为每个选择都会细化其余条件。您不必为每个组件进行选择。
+
.. 完成后，单击*查看结果*以查看搜索条件支持的配置。


. 您还可以在*简化的ONTAP SAN主机*中执行以下操作：
+
.. 单击书籍图标可查看适用于您选择的策略和准则。
.. 单击链图标可为您的选择生成一个可共享的URL、您可以与其他人共享此URL。
.. 选择撤消图标以清除所有选择并重新开始。


. 在结果屏幕中、您可以执行以下操作：
+
.. 查看有关您的配置的详细信息、警报和信息通知。
.. 单击星号图标将此搜索设为收藏项。命名并描述配置。这将成为保存的搜索，可从*保存的搜索*菜单中查看。您也可以在此处订阅配置、更改后会通知您。如果您订阅，您还会在*subscribes*菜单下看到此列表。
.. 将鼠标悬停在*使用*构建端到端视图上可查找其他受支持的解决方案。
.. 单击*What if*以更改组件并浏览其他兼容性选项。



